flowchart TD
    %% Начало работы с тестами
    Start["Начало работы"] 
    Start --> A("Пишем новый (или изменяем) код приложения (или тест)")
   
    %% Запуск тестов
    A --> B["Запускаем: flutter test"]
    B --> C{"Тест прошел?"}
    
    %% Обработка результатов теста
    C -->|Да| D["Коммитим изменения"]
    C -->|Нет| E["Переходим к исправлению"]

    %% Дифф и обновление
    E --> F{"Есть дифф?"}
    F -->|Да| G["Проверяем дифф"]
    F -->|Нет| H["Исправляем ошибку"]
    
    %% Проверка изменений
    G --> I{"Изменения ожидаемы?"}
    I -->|Да| J["Обновляем образцы с помощью flutter test --update-goldens"]
    I -->|Нет| K["Разбираемся с проблемой"] 
    K --> A

    %% Повторный запуск тестов
    J --> B

    %% Завершение работы
    D --> M["Конец работы"]
    H --> A

    %% Определение стилей
    classDef startEnd fill:#ffcccc,stroke:#333,stroke-width:2px;
    classDef decision fill:#ccffcc,stroke:#333,stroke-width:2px;
    classDef action fill:#ccddff,stroke:#333,stroke-width:2px;
    class Start,M startEnd;
    class C,F,I decision;
    class A,B,D,E,G,H,J,K action;
